### ISSUE TITLE
Importing user data from KA may be broken

### ISSUE THREAD

**Issue by jamalex** [fle-internal/ka-lite-central#179]
```
Traceback (most recent call last):

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/var/www/ka-lite-central/centralserver/../centralserver/khanload/api_views.py", line 149, in update_all_central_callback
    video_id = get_video_id(youtube_id)  # map from youtube_id to video_id (across all languages)

NameError: global name 'get_video_id' is not defined
```

Looks like it should be a fairly straightforward fix -- would you be able to have a look, @aronasorman? Thanks!

**Comment by aronasorman** [comment]
I'm not sure if this is still a priority, so closing for now. Let me know if we still ever plan to do this :P
