### ISSUE TITLE
Registering twice with the same database throws an ugly error

### ISSUE THREAD

**Issue by jamalex** [fle-internal/ka-lite-central#240]
If an unregistered database is cloned, and used in multiple installations, and then more than one of them tries to register, the following error is thrown on the central server (and an ugly message is displayed on the distributed server side):

```
Traceback (most recent call last):
  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/securesync/devices/api_views.py", line 99, in register_device
    device_zone.save()     # create the DeviceZone for the new device, with an 'upgraded' signature
  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/securesync/engine/models.py", line 379, in save
    self.sign(device=own_device)
  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/securesync/engine/models.py", line 249, in sign
    self.full_clean()  # make sure the model data is of the appropriate types
  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/securesync/engine/models.py", line 237, in full_clean
    return super(SyncedModel, self).full_clean(exclude=exclude)
  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/db/models/base.py", line 926, in full_clean
    raise ValidationError(errors)
ValidationError: {'id': [u'Device zone with this Id already exists.']}
```

This has become a particular problem since discovering that we have been shipping a Windows installer with an included (or otherwise duplicate) database.

Proposed solution: catch this exception on the central server and return a useful message that will end up getting displayed in the distributed app, explaining the problem and possible remedies.

**Comment by MCGallaspy** [comment]
@jamalex in `0.12.10` I keep getting the same error, even with "fresh" databases. Leads me to believe its a genuine error with the central server.
