### ISSUE TITLE
Coach reports failing to load properly on central server

### ISSUE THREAD

**Issue by jamalex** [fle-internal/ka-lite-central#254]
When loading: http://staging.learningequality.org/coachreports/table/exercise/?topic=addition-subtraction&facility_id=&group_id=<...>

I get the following error:

```
  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/kalite/shared/decorators/auth.py", line 42, in require_login_wrapper_fn
    return handler(request, *args, **kwargs)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/kalite/shared/decorators/auth.py", line 62, in require_admin_wrapper_fn
    return handler(request, *args, **kwargs)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/kalite/shared/decorators/auth.py", line 137, in require_authorized_admin_wrapper_fn_central
    return handler(request, *args, **kwargs)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/annoying/decorators.py", line 79, in wrapper
    context_instance=RequestContext(request), mimetype=mimetype)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/loader.py", line 177, in render_to_string
    return t.render(context_instance)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 140, in render
    return self._render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 833, in render
    bit = self.render_node(node, context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 847, in render_node
    return node.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 833, in render
    bit = self.render_node(node, context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 847, in render_node
    return node.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 833, in render
    bit = self.render_node(node, context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 847, in render_node
    return node.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 833, in render
    bit = self.render_node(node, context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 847, in render_node
    return node.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 833, in render
    bit = self.render_node(node, context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 847, in render_node
    return node.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 833, in render
    bit = self.render_node(node, context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 847, in render_node
    return node.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 833, in render
    bit = self.render_node(node, context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 847, in render_node
    return node.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/defaulttags.py", line 284, in render
    return nodelist.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 833, in render
    bit = self.render_node(node, context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 847, in render_node
    return node.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/defaulttags.py", line 284, in render
    return nodelist.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 833, in render
    bit = self.render_node(node, context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 847, in render_node
    return node.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/loader_tags.py", line 156, in render
    return self.render_template(self.template, context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/loader_tags.py", line 138, in render_template
    output = template.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 140, in render
    return self._render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 833, in render
    bit = self.render_node(node, context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/base.py", line 847, in render_node
    return node.render(context)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/defaulttags.py", line 195, in render
    nodelist.append(node.render(context))

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/template/defaulttags.py", line 424, in render
    raise e

NoReverseMatch: Reverse for 'learn' with arguments '()' and keyword arguments '{}' not found.
```

And on the api endpoint: /coachreports/api/playlist_progress/ I get the traceback:

```
Traceback (most recent call last):
  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/tastypie/resources.py", line 195, in wrapper
    response = callback(request, *args, **kwargs)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/tastypie/resources.py", line 426, in dispatch_list
    return self.dispatch('list', request, **kwargs)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/tastypie/resources.py", line 458, in dispatch
    response = method(request, **kwargs)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/tastypie/resources.py", line 1266, in get_list
    objects = self.obj_get_list(bundle=base_bundle, **self.remove_api_resource_names(kwargs))

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/kalite/coachreports/api_resources.py", line 86, in obj_get_list
    return self.get_object_list(bundle.request)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/kalite/coachreports/api_resources.py", line 81, in get_object_list
    result = PlaylistProgress.user_progress(user_id=user_id)

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/kalite/coachreports/models.py", line 182, in user_progress
    progress["url"] = reverse("learn") + p.get("path")

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/core/urlresolvers.py", line 496, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))

  File "/var/www/ka-lite-central/centralserver/../ka-lite-submodule/python-packages/django/core/urlresolvers.py", line 416, in _reverse_with_prefix
    "arguments '%s' not found." % (lookup_view_s, args, kwargs))

NoReverseMatch: Reverse for 'learn' with arguments '()' and keyword arguments '{}' not found.
```

**Comment by jamalex** [comment]
@rtibbles Looks like this is to do with some refactoring on the links/paths? Any ideas?
